In [1]:
import numpy as np
import pandas as pd

# This file should be run only once to initialize working excel table
# Please do not run it again

In [2]:
orig_inputs = np.load('initial_inputs.npy')

In [3]:
orig_outputs = np.load('initial_outputs.npy')

In [4]:
df = pd.DataFrame(orig_inputs, columns = ['x1','x2','x3','x4','x5'])

In [5]:
df['y'] = pd.DataFrame(orig_outputs, columns = ['y'])

In [6]:
df.to_excel('data6.xlsx', index=False)

In [7]:
#df2 = pd.read_excel('data6.xlsx')

In [8]:
df2

          x1        x2        x3        x4        x5         y
0   0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265
1   0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955
2   0.729523  0.748106  0.679775  0.356552  0.671054 -1.672200
3   0.770620  0.114404  0.046780  0.648324  0.273549 -1.536058
4   0.618812  0.331802  0.187288  0.756238  0.328835 -0.829237
5   0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049
6   0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786
7   0.945069  0.288459  0.978806  0.961656  0.598016 -1.694343
8   0.125720  0.862725  0.028544  0.246605  0.751206 -2.571170
9   0.757594  0.355831  0.016523  0.434207  0.112433 -1.309116
10  0.536797  0.308781  0.411879  0.388225  0.522528 -1.144785
11  0.957740  0.235669  0.099146  0.156806  0.071317 -1.912677
12  0.629308  0.803484  0.811408  0.045613  0.110624 -1.622839
13  0.021735  0.428084  0.835939  0.489489  0.511082 -1.356682
14  0.439344  0.698924  0.426820  0.109476  0.877888 -2.018425
15  0.258906  0.793678  0.642114  0.196673  0.593103 -1.702558
16  0.432166  0.715618  0.341819  0.705000  0.614962 -1.294247
17  0.782880  0.536336  0.443284  0.859700  0.010326 -0.935757
18  0.921776  0.931871  0.414876  0.595057  0.735626 -2.155768
19  0.126679  0.291470  0.064528  0.680515  0.892819 -1.746882