In [1]:
import numpy as np
import pandas as pd

# This file should be run only once to initialize working excel table
# Please do not run it again

In [2]:
orig_inputs = np.load('initial_inputs.npy')

In [3]:
orig_outputs = np.load('initial_outputs.npy')

In [4]:
orig_inputs

array([[0.19144708, 0.03819337, 0.60741781, 0.41458414],
       [0.75865295, 0.53651774, 0.65600038, 0.36034155],
       [0.43834987, 0.8043397 , 0.21024527, 0.15129482],
       [0.70605083, 0.53419196, 0.26424335, 0.48208755],
       [0.83647799, 0.19360965, 0.6638927 , 0.78564888],
       [0.68343225, 0.11866264, 0.82904591, 0.56757661],
       [0.55362148, 0.66734998, 0.32380582, 0.81486975],
       [0.35235627, 0.32224153, 0.11697937, 0.47311252],
       [0.15378571, 0.72938169, 0.42259844, 0.44307417],
       [0.46344227, 0.63002451, 0.10790646, 0.9576439 ],
       [0.67749115, 0.35850951, 0.47959222, 0.07288048],
       [0.58397341, 0.14724265, 0.34809746, 0.42861465],
       [0.30688872, 0.31687813, 0.62263448, 0.09539906],
       [0.51114177, 0.817957  , 0.72871042, 0.11235362],
       [0.43893338, 0.77409176, 0.37816709, 0.93369621],
       [0.22418902, 0.84648049, 0.87948418, 0.87851568],
       [0.72526172, 0.47987049, 0.08894684, 0.75976022],
       [0.35548161, 0.63961937, 0.41761768, 0.12260384],
       [0.11987923, 0.86254031, 0.64333133, 0.84980383],
       [0.12688467, 0.15342962, 0.77016219, 0.19051811]])

In [5]:
df = pd.DataFrame(orig_inputs, columns = ['x1','x2','x3','x4'])

In [6]:
df['y'] = pd.DataFrame(orig_outputs, columns = ['y'])

In [7]:
df.to_excel('data5.xlsx', index=False)

In [8]:
#df2 = pd.read_excel('data5.xlsx')

In [9]:
df2

          x1        x2        x3        x4            y
0   0.191447  0.038193  0.607418  0.414584    64.443440
1   0.758653  0.536518  0.656000  0.360342    18.301380
2   0.438350  0.804340  0.210245  0.151295     0.112940
3   0.706051  0.534192  0.264243  0.482088     4.210898
4   0.836478  0.193610  0.663893  0.785649   258.370525
5   0.683432  0.118663  0.829046  0.567577    78.434389
6   0.553621  0.667350  0.323806  0.814870    57.571537
7   0.352356  0.322242  0.116979  0.473113   109.571876
8   0.153786  0.729382  0.422598  0.443074     8.847992
9   0.463442  0.630025  0.107906  0.957644   233.223610
10  0.677491  0.358510  0.479592  0.072880    24.423088
11  0.583973  0.147243  0.348097  0.428615    64.420147
12  0.306889  0.316878  0.622634  0.095399    63.476716
13  0.511142  0.817957  0.728710  0.112354    79.729130
14  0.438933  0.774092  0.378167  0.933696   355.806818
15  0.224189  0.846480  0.879484  0.878516  1088.859618
16  0.725262  0.479870  0.088947  0.759760    28.866752
17  0.355482  0.639619  0.417618  0.122604    45.181570
18  0.119879  0.862540  0.643331  0.849804   431.612757
19  0.126885  0.153430  0.770162  0.190518     9.972332